# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

default_platform :ios

platform :ios do
  before_all do
    update_fastlane
    
    if is_ci?
      cocoapods
    end
  end
  
  desc "Travis CI"
  lane :travis do
    test
  end
  
  desc "Build"
  lane :build do
    increment_build_number build_number: Time.new.strftime("%Y%m%d.%H%M%S")
    
    gym(
      workspace: "TartuWeatherTV.xcworkspace",
      scheme: "TartuWeatherTV",
      configuration: "Release",
      clean: true,
      output_name: "TartuWeatherTV.ipa"
    )
    
    dsym_zip
    
    copy_artifacts(
      target_path: 'artifacts',
      artifacts: ['*.dSYM.zip']
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: "TartuWeatherTV.xcworkspace",
      scheme: "TartuWeatherTV",
      configuration: "Debug",
      xcargs: "CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO"
    )
  end

end
